name: bondtime
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  cloud_functions: ^5.3.4
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  http: ^1.3.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/21864181_6502439 1.svg
    - assets/fonts/
    - assets/images/email.svg
    - assets/images/pw.svg
    - assets/images/apple.svg
    - assets/images/google.svg
    - assets/images/facebook.svg

  fonts:
    - family: InterTight
      fonts:
        - asset: assets/fonts/InterTight-VariableFont_wght.ttf
        - asset: assets/fonts/InterTight-Italic-VariableFont_wght.ttf
          style: italic
